// ignore_for_file: lines_longer_than_80_chars
// File generated by FlutterFire CLI + customized for SynapseTrade.
// Run: flutterfire configure  (after setting up Firebase project)
// ─────────────────────────────────────────────────────────────────
// IMPORTANT: Replace the placeholder values below with the real config
// from your Firebase project: https://console.firebase.google.com
// Project: SynapseTrade  →  Project Settings → Your apps
// ─────────────────────────────────────────────────────────────────

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ── iOS ──────────────────────────────────────────────────────────────────

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNNeDCJ3b3Tc1W-w6AFTCpwcGHZV_hHBw',
    appId: '1:326007010368:ios:604a4207d5936b0c969ba5',
    messagingSenderId: '326007010368',
    projectId: 'synapsetradedev-1',
    storageBucket: 'synapsetradedev-1.firebasestorage.app',
    iosClientId: '326007010368-4dc7i37lt1riojrg9ditd065d8qs73a3.apps.googleusercontent.com',
    iosBundleId: 'com.synapsetrade.synapseTrade',
  );

  // Get from: Firebase Console → Project Settings → Your apps → iOS → GoogleService-Info.plist

  // ── Android ───────────────────────────────────────────────────────────────

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmSIIeXAPW1Tj5LoctnAijg6-8Pl7MsoY',
    appId: '1:326007010368:android:b04da1c3caec1a24969ba5',
    messagingSenderId: '326007010368',
    projectId: 'synapsetradedev-1',
    storageBucket: 'synapsetradedev-1.firebasestorage.app',
  );

  // Get from: Firebase Console → Project Settings → Your apps → Android → google-services.json

  // ── Web ───────────────────────────────────────────────────────────────────
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'REPLACE_WITH_WEB_API_KEY',
    appId: 'REPLACE_WITH_WEB_APP_ID',
    messagingSenderId: 'REPLACE_WITH_SENDER_ID',
    projectId: 'synapsetrade-app',
    storageBucket: 'synapsetrade-app.appspot.com',
    authDomain: 'synapsetrade-app.firebaseapp.com',
  );

  // ── macOS (if needed) ─────────────────────────────────────────────────────
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'REPLACE_WITH_MACOS_API_KEY',
    appId: 'REPLACE_WITH_MACOS_APP_ID',
    messagingSenderId: 'REPLACE_WITH_SENDER_ID',
    projectId: 'synapsetrade-app',
    storageBucket: 'synapsetrade-app.appspot.com',
    iosBundleId: 'com.synapsetrade.app',
    iosClientId: 'REPLACE_WITH_MACOS_CLIENT_ID',
  );
}