// ignore_for_file: lines_longer_than_80_chars
// File generated by FlutterFire CLI + customized for SynapseTrade.
// Run: flutterfire configure  (after setting up Firebase project)
// ─────────────────────────────────────────────────────────────────
// IMPORTANT: Replace the placeholder values below with the real config
// from your Firebase project: https://console.firebase.google.com
// Project: SynapseTrade  →  Project Settings → Your apps
// ─────────────────────────────────────────────────────────────────

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ── iOS ──────────────────────────────────────────────────────────────────
  // Get from: Firebase Console → Project Settings → Your apps → iOS → GoogleService-Info.plist
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'REPLACE_WITH_IOS_API_KEY',
    appId: 'REPLACE_WITH_IOS_APP_ID',
    messagingSenderId: 'REPLACE_WITH_SENDER_ID',
    projectId: 'synapsetrade-app',
    storageBucket: 'synapsetrade-app.appspot.com',
    iosBundleId: 'com.synapsetrade.app',
    iosClientId: 'REPLACE_WITH_IOS_CLIENT_ID',
  );

  // ── Android ───────────────────────────────────────────────────────────────
  // Get from: Firebase Console → Project Settings → Your apps → Android → google-services.json
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'REPLACE_WITH_ANDROID_API_KEY',
    appId: 'REPLACE_WITH_ANDROID_APP_ID',
    messagingSenderId: 'REPLACE_WITH_SENDER_ID',
    projectId: 'synapsetrade-app',
    storageBucket: 'synapsetrade-app.appspot.com',
  );

  // ── Web ───────────────────────────────────────────────────────────────────
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'REPLACE_WITH_WEB_API_KEY',
    appId: 'REPLACE_WITH_WEB_APP_ID',
    messagingSenderId: 'REPLACE_WITH_SENDER_ID',
    projectId: 'synapsetrade-app',
    storageBucket: 'synapsetrade-app.appspot.com',
    authDomain: 'synapsetrade-app.firebaseapp.com',
  );

  // ── macOS (if needed) ─────────────────────────────────────────────────────
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'REPLACE_WITH_MACOS_API_KEY',
    appId: 'REPLACE_WITH_MACOS_APP_ID',
    messagingSenderId: 'REPLACE_WITH_SENDER_ID',
    projectId: 'synapsetrade-app',
    storageBucket: 'synapsetrade-app.appspot.com',
    iosBundleId: 'com.synapsetrade.app',
    iosClientId: 'REPLACE_WITH_MACOS_CLIENT_ID',
  );
}
